### ISSUE TITLE
Newer Gem

### ISSUE THREAD

**Issue by arbox** [peterc/trtl#4]
Hi @peterc ,

could you please upload the updated version to Rubygems (0.0.2 vs. actual 0.0.1).

I desperately need it :) The whole evening now moving the turtle )))

**Comment by peterc** [comment]
Great news, I've just made some tweaks to get it all working nicely on Ruby 2.4 and have released a new version to RubyGems as well :) Thanks!

**Comment by arbox** [comment]
@peterc Thank you! I've played a bit with the source version and with the newer gem. Somehow no window appears ... But it's probably my local Ubuntu problem.
